### ISSUE TITLE
Which one is recommended for beginners?

### ISSUE THREAD

**Issue by flatsiedatsie** [curtpw/nRF5x-device-reverse-engineering#1]
Does any watch stand out so far? 

Factors I can imagine being relevant:
- Easy to open, or an open wireless DFU
- Pins already mapped
- Popular choice so far

**Comment by curtpw** [comment]
I would go with the X9. All the tutorials ( https://hackaday.io/project/144350-hack-35-activity-trackers-for-mental-health-more ) are geared towards the X9. The PCB test pads are big and easy to solder. The HR sensor is a simple LED/Photosensor breakout. Haven't gotten DFU working yet, that is definitely on the list.
