### ISSUE TITLE
ID115Plus

### ISSUE THREAD

**Issue by Mis012** [curtpw/nRF5x-device-reverse-engineering#11]
https://www.ebay.com/itm/Smartarmband-mit-Pulsmesser-Armbanduhr-Wasserdicht-IP67Fitness-Tracker-Sportband/302909343907

I saw this ^, it seems there are versions with and without the nrf chip, but this one has it listed, so it should be fine.
If I buy this, is it certain I can OWN it with more or less work?
Also, can RPi zero be used as a programmer?

Thanks for your help :)

**Comment by Mis012** [comment]
well, there was no nrf chip in this, shame :/
it had swd though, even uart, but I coyldn't find any info on the chip. And I managed to crack the screen...
I'll go for x9 pro, that one should be fine unless I screw something up ;)

**Comment by GeorgeHahn** [comment]
@Mis012 My observation has been that the really cheap devices (<~100RMB) do not contain nRF5x devices, even if the copy-pasted description claims it. I'd be interested in pictures of this device's circuit board if you don't mind uploading some to this issue!

**Comment by Mis012** [comment]
![img_20181120_165940](https://user-images.githubusercontent.com/10321751/48798329-b2c97780-ed04-11e8-8f6a-e66f03a7e033.jpg)
![img_20181120_170028](https://user-images.githubusercontent.com/10321751/48798331-b2c97780-ed04-11e8-93b7-8ec8dfbe7ec7.jpg)
![img_20181120_170233](https://user-images.githubusercontent.com/10321751/48798332-b2c97780-ed04-11e8-9a5c-f88a87c2ceab.jpg)

**Comment by scientistnobee** [comment]
What fitness sensor it is?

**Comment by Mis012** [comment]
What I have is the e-bay page (copy pasted from id115 description, I thought they would copy the hardware as well jerks) and those photos.

"words" that may be related:
mcube
yoho
ms1020

**Comment by Mis012** [comment]
also, this ip was in the apk (I will base64 encode it to search-engine-proof it):
aHR0cDovLzEyMS40MC45Ni4xNzEvCg==
and
aHR0cDovLzEyMS40MC45Ni4xNzEvZWRpbWFnZS8K
feel free to have fun with this:
aHR0cDovLzEyMS40MC45Ni4xNzEvZWRpbWFnZS8yMDE3LTA3LTA2LzIwMTcwNzA2MjA0MjI2Njg3
MDYuanNwCg==
(the few days ago stuff is me poking around)
