### ISSUE TITLE
Do you want doc for another smart band ?

### ISSUE THREAD

**Issue by nessotrin** [curtpw/nRF5x-device-reverse-engineering#2]
I have taken appart a Inchor HR2. I scrapped the project because the screen had no public datasheet and the company didn't answer my emails. Do you want photos or documentation ?

As a side note, I'm still searching for a smartband with a least touch, screen amd bluetooth functionnality. The X9 pro seems to be complete, but I would prefer a vertical screen type. Do you think you will have more info on the others quickly, or should I go for the X9 ? I'm planning on writting an micro OS from scratch (for fun and learning), everything open-source, I'll send the link to you when done.

**Comment by curtpw** [comment]
I would love documentation on additional nRF51822 and nRF52832 devices. You can just add a folder for your additional device and make a pull request. I'll probably wait on merging until basic GPIO pinout can be identified though. Let me take a look at what you have and I'll see if I can quickly deduce component ID and pinout.

In terms of a vertical screen, take a look at the N68. Its almost identical to the X9 but with a taller screen and a smaller form factor.  All the examples for the X9 will work for the N68 with GPIO modification. The only exception is OLED display which is untested on the N68.
